apiVersion: v1
kind: Namespace
metadata:
  name: hacker-company

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: hacker-company
  labels:
    buster: data
    role: data
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: data
  namespace: hacker-company
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 16379
  selector:
    role: data
